"""
Flask application for the Code Explanation Tool.

This module sets up a simple web interface for users to input Python code
and receive explanations generated by the tool.
"""

from flask import Flask, render_template, request, jsonify
from src.main import explain_code

app = Flask(__name__)

@app.route('/', methods=['GET', 'POST'])
def index():
    """
    Handle GET and POST requests to the main page.

    For GET requests, render the main page.
    For POST requests, process the submitted code and return the explanation.

    Returns:
        str: Rendered HTML template for GET requests.
        json: JSON object containing the code explanation for POST requests.
    """
    if request.method == 'POST':
        code = request.form['code']
        explanation = explain_code(code)
        return jsonify({'explanation': explanation})
    return render_template('index.html')

if __name__ == '__main__':
    app.run(debug=True)
